version: '3'
services:
  ionic:
    build:
      context: '.'
      args:
      - 'NODEJS_VERSION=${NODEJS_VERSION}'
    volumes:
      - ${APP_CODE_PATH_HOST}:/src
    # command: ionic serve
    ports:
      - "${IONIC_HTTP_PORT}:8100"
volumes: {}
