name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Nodejs 16
      run: docker-compose build
      env:
        NODEJS_VERSION: 16


    - name: Build the Docker image Nodejs 17
      run: docker-compose build
      env:
        NODEJS_VERSION: 17


    - name: Build the Docker image Nodejs 18
      run: docker-compose build
      env:
        NODEJS_VERSION: 18


    - name: Build the Docker image Nodejs 19
      run: docker-compose build
      env:
        NODEJS_VERSION: 19